### ISSUE TITLE
Cannot read property 'red' of undefined

### ISSUE THREAD

**Issue by moltak** [warsclon/acra-node-server#2]
Hi guys.  I try to start acra-node-server, but it has a bug.
Look at this.

console.log("port_web:"+portWeb.red);
                                                      ^
TypeError: Cannot read property 'red' of undefined
    at Object.<anonymous> (/home/moltak/acra-node-server/properties.js:31:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/moltak/acra-node-server/appAcra.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

How can I fix it?

ps. I set a properties.js and execute npm install.

**Comment by warsclon** [comment]
Hi, The problems is the package.json, you need import the colors package.

npm import colors

I will fix the package.json ASAP.

Regards!
